name: RSpec Tests

on:
  # pull_request:
  #   branches: [develop]
  push:
    branches-ignore:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: good_body_user
          POSTGRES_PASSWORD: myapp_password
          POSTGRES_DB: good_body_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create test database
        run: |
          psql -c 'CREATE DATABASE good_body_test;' -h localhost -p 5432
          psql -c "CREATE USER good_body_user WITH PASSWORD 'myapp_password';" -h localhost -p 5432 -U postgres
          psql -c "GRANT ALL PRIVILEGES ON DATABASE good_body_test TO good_body_user;" -h localhost -p 5432 -U postgres

      - name: Run RSpec tests
        run: |
          bundle exec rspec
      
      - name: Drop test database
        run: |
          psql -c 'DROP DATABASE good_body_test;' -h localhost -p 5432