name: RSpec Tests

on:
  # pull_request:
  #   branches: [develop]
  push:
    branches-ignore:
      - develop
jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Create and setup test database
      run: |
        psql -c 'CREATE DATABASE myapp_test;' -U postgres -h localhost -p 5432
        psql myapp_test < db/structure.sql
    - name: Run RSpec tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp_test
      run: |
        bundle exec rspec spec